apiVersion: v1
kind: Service
metadata:
  name: springapp-service
spec:
  selector:
    app: springapp
  ports:
    - protocol: "TCP"
      port: 8085
      targetPort: 8085
      nodePort: 32567
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
spec:
  selector:
    matchLabels:
      app: springapp
  replicas: 2
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
        - name: springapp
          image: mertcakmak2/hello-spring:2
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
